### ISSUE TITLE
decimal as comma does not work

### ISSUE THREAD

**Issue by chrisschd** [kartik-v/yii2-money#10]
Hello,
First: great extention, thanks!

So if I use the widget with comma es decimal point it doesn't work. I've used the new version (5days ago) from the plentz/jquery-maskmoney repository but it doen's fix the issue.

 $form->field($model, 'discount')->widget(MaskMoney::classname(), [
'pluginOptions' => [
'prefix' => '',
'suffix' => ' €',
'allowNegative' => false,
        'thousands' => '.',
        'decimal' => ',',
        'precision' => 2,
]
]);

The value was't parsed correct. (new jquery file from plentz rep.):
For Example: I've the value 2.1 in the model->discount then it shows "21,00€"

With the old jquery file:
For Example: I've the value 2.1 in the model then it shows "0,02€"
A work around was to manipulate the value with *100 to show the correct value, but then it saves 210 in the database when the field wasn't touched. (ok /100 will fixe them but ==>) If a manipulate the filed to for example 4,5 it will write the correct value 4.5 in the database ... 
How can I use the widget in a right way?

Thanks!

**Comment by rubenheymans** [comment]
your solution works, thanks

**Comment by kartik-v** [comment]
Resolved via [updates & enhancements to release v1.2.2](https://github.com/kartik-v/yii2-money/commit/6c18c47b6561e52ecd4cff9d2e0c3a0e974c236f). Duplicate to #25, #11.
