### ISSUE TITLE
remove attribute "name" from the text field generated by yii2-money ?

### ISSUE THREAD

**Issue by michaelnguyen547** [kartik-v/yii2-money#15]
When doing a form submission, I only need the non-format value to be submitted to reduce the data transfer. In the code below, the extra **'input' tag** added by yii2-money should not have **"name"** attribute. No need to use it at all. 

``` html
<input type="text" id="st-hours-id-disp" class="form-control" name="st-hours-id-disp" value="0">
<input type="hidden" id="st-hours-id" class="form-control" name="TimeEntry[st_hours]" value="0" data-krajee-maskmoney="maskMoney_e39e533b">
```

Ideally, it should be

``` html
<input type="text" id="st-hours-id-disp" class="form-control"  value="0">
<input type="hidden" id="st-hours-id" class="form-control" name="TimeEntry[st_hours]" value="0" data-krajee-maskmoney="maskMoney_e39e533b">
```

**Comment by kartik-v** [comment]
Resolved via [updates & enhancements to release v1.2.2](https://github.com/kartik-v/yii2-money/commit/6c18c47b6561e52ecd4cff9d2e0c3a0e974c236f). New property `displayInputName` is added for you to set what you want.
