### ISSUE TITLE
Question: Why plugin maskMoney and not maskedInput

### ISSUE THREAD

**Issue by Enrica-r** [kartik-v/yii2-money#2]
The idea with the two fields (formatted and unformatted) like datecontrol is consequent and good.

But I hate maskMoney plugin. As also in their issue list criticized you need to enter the decimals always. Example: You want to enter $25 only --> you input must be 2500 or $425.40 --> enter 42540. The dot as key isn't accepted. This behaviour isn't intuitive and you have to check what you have entered otherwiese your have $42.54 in our example.

Masked Input with alias 'decimal' is much better. The only disadvantage is that you can't limit the number of precision and decimals like (m,n) -> eg. (7,2) --> 99,999.99 maximal according to database specification of MySQL and others.

Do you see a quick solution with Masked Input without changing there code or shall I copy a part of their complex code and build an own javascript? What do you think?
Regards,
Enrica again.

**Comment by kartik-v** [comment]
New extension **kartik-v/yii2-number** has been created.

**Comment by kartik-v** [comment]
The new [yii2-number extension](http://demos.krajee.com/number) has been released and is now a replacement for the yii2-money extension. Recommend to head over to use that extension.
