### ISSUE TITLE
This is not working for me

### ISSUE THREAD

**Issue by rubenheymans** [kartik-v/yii2-money#22]
These are my settings:

```
'maskMoneyOptions' => [
        'prefix' => '',
        'suffix' => ' €',
        'affixesStay' => true,
        'thousands' => ' ',
        'decimal' => ',',
        'precision' => 2,
        'allowZero' => false,
        'allowNegative' => false,
    ],
```

I changed line 109 in MaskMoney.php to
`var val = parseFloat({$idSave}.val()) * 100;`

Now it's working, can you check this, or at least change `private $_displayOptions = [];` to `protected` so I can overwrite this myself.
Thanks

**Comment by kartik-v** [comment]
Resolved via [updates & enhancements to release v1.2.2](https://github.com/kartik-v/yii2-money/commit/6c18c47b6561e52ecd4cff9d2e0c3a0e974c236f). Duplicate to #26, #23, #16, #9.
