### ISSUE TITLE
use the latest jquery-maskmoney

### ISSUE THREAD

**Issue by michaelnguyen547** [kartik-v/yii2-money#25]
jquery-maskmoney current release is v3.1.1 [ https://github.com/plentz/jquery-maskmoney ]

your copy of jquery-maskmoney is v3.0.2 

how can I upgrade yii2-money to use jquery-maskmoney latest version ?

**Comment by kartik-v** [comment]
Resolved via [updates & enhancements to release v1.2.2](https://github.com/kartik-v/yii2-money/commit/6c18c47b6561e52ecd4cff9d2e0c3a0e974c236f). Duplicate to #11, #10.
