### ISSUE TITLE
FYI on (maybe) related masked money plugin

### ISSUE THREAD

**Issue by michaelnguyen547** [kartik-v/yii2-money#29]
https://github.com/plentz/jquery-maskmoney/issues/231

This drive me nuts as it is working on Windows 10 machine , but not on Chrome/Safari on MacOS Sierra

When 'prefix' is empty (''), the following happens:
* cursor need to be to the left of the decimal in order to enter a number. When the cursor at the far right (e.g. 0.00 <- cursor stay after the 3rd zero), pressing 0 - 4 does nothing, pressing 5 to 9 increase to (0.01)
* cursor to the left of the decimal, I can enter number but only 4 max, then it resets to 0
e.g. I can enter 9999.00, when I do 99999.00, it will become 0.00

**Comment by ilbassa** [comment]
Hi, I have the same problem here with prefix empty.

**Comment by hagenr** [comment]
Yes, driving me nuts. Took ages to find out it was the mask js
downgrade to 3.0.2 maybe.by now i changed the js myself

**Comment by kartik-v** [comment]
The new [yii2-number extension](http://demos.krajee.com/number) has been released and is now a replacement for the yii2-money extension. Recommend to head over to use that extension. Related #2, #32, #33.
