### ISSUE TITLE
"German Amount" bug

### ISSUE THREAD

**Issue by knightmr** [kartik-v/yii2-money#30]
I can't change the value without defining a suffix.

My params:
    'maskMoneyOptions' => [
        'prefix' => '',
        'suffix' => '',
        'affixesStay' => false,
        'thousands' => '.',
        'decimal' => ',',
        'precision' => 2,
        'allowZero' => true,
        'allowNegative' => false,
    ]

**Comment by iluxaar** [comment]
Not working value > 9999, then prefix = ''.
How use without prefix?

**Comment by kartik-v** [comment]
The new [yii2-number extension](http://demos.krajee.com/number) has been released and is now a replacement for the yii2-money extension. Recommend to head over to use that extension. Related #2, #32, #33.
