### ISSUE TITLE
Behavior Client-Side Validation

### ISSUE THREAD

**Issue by hagenr** [kartik-v/yii2-money#31]
If i submit the form within a MaskMoney Input, the validate Event of Clientside Validation of Yiiactiveform is fired before the MaskMoney can update the value within its hidden field.
Resulting in an erroneuos Message (e.g. "Value cant be empty")

Is there any workaround or what a i doing wrong?

PS: I used the old maskmoney.js because of #29

**Comment by kartik-v** [comment]
The new [yii2-number extension](http://demos.krajee.com/number) has been released and is now a replacement for the yii2-money extension. Recommend to head over to use that extension. Related #2, #32, #33.
