### ISSUE TITLE
Stopped working after v1.2.2 update with an empty `prefix`

### ISSUE THREAD

**Issue by ricpelo** [kartik-v/yii2-money#33]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-money.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/money).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Within an ActiveForm, I put the following simple field:

```php
<?= $form->field($model, 'price')->widget(MaskMoney::classname(), [      
        'pluginOptions' => [                                                    
        'prefix' => '',                                                         
        'suffix' => ' $',                                                          
        'allowNegative' => false                                                
    ]                                                                              
]) ?>                                                                           
```

## Expected behavior and actual behavior

The field behaves bad when I type digits (digits dissappears and so on).

I was expecting to work OK as before.

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-money version: v1.2.2, dev-master

## Isolating the problem

- [x] This bug doesn't happens [on the demos page](https://demos.krajee.com/money) because it doesn't have a demo with an empty prefix.
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-money without other plugins.

**Comment by ricpelo** [comment]
In Yii's [UPGRADE.md](https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2011) file, I can see:

> Inputmask package name was changed from jquery.inputmask to inputmask. If you've configured path to assets manually, please adjust it.

Maybe that's the source of the problem?

**Comment by ricpelo** [comment]
Doing `git bisect` I found the commit which introduces the issue: yiisoft/yii2@7bf53539c .

**Comment by ricpelo** [comment]
Forget it. The problem is in the library, not Yii. Sorry.

**Comment by ricpelo** [comment]
I've found the origin of the problem.

These lines tries to fix an issue but introduces a regression when `prefix` is empty:

https://github.com/kartik-v/yii2-money/blob/e783ca66d2ec83decc2b53d571b7cda744bbd17f/assets/js/jquery.maskMoney.js#L525-L528

The fix it try to fix seems to be fixed upstream:

https://github.com/plentz/jquery-maskmoney/blob/cdbeeac5a3a6042db3f94ad44e0cf7f93a51c149/src/jquery.maskMoney.js#L530-L536

I'm going to build a PR to fix this issue.

**Comment by kartik-v** [comment]
The new [yii2-number extension](http://demos.krajee.com/number) has been released and is now a replacement for the yii2-money extension. Recommend to head over to use that extension. Related #2, #33.

**Comment by Commifreak** [comment]
> The new yii2-number extension has been released and is now a replacement for the yii2-money extension. Recommend to head over to use that extension. Related #2, #32.

Then please mark this plugin as deprecated and suggest yii2-number ;)
