### ISSUE TITLE
Garbage input Value on `"reverse"=>true`

### ISSUE THREAD

**Issue by buttflattery** [kartik-v/yii2-money#35]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-money.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/money).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Install the extension
2. set the configuration in the params 
3. set the `"reverse"=>true` in the configurations.

```
'maskMoneyOptions' => [
        'prefix' => '$ ',
        'suffix' => ' US',
        'affixesStay' => true,
        'thousands' => ',',
        'decimal' => '.',
        'precision' => 2,
        'allowZero' => false,
        'allowNegative' => false,
        'reverse' => true,
    ],
```
4 Create an input and apply the widget 
```
echo $form->field(
    $model,
    'amount',
    [
        'template' => '<div class="form-line">{input}{label}</div>{error}',
        'inputOptions' => ['class' => 'no-resize form-control', 'useSessionFlash' => true],
    ]
)
    ->widget(MaskMoney::class)
    ->label(false, ['class' => 'form-label']);
```

## Expected behavior and actual behavior

When I follow those steps, I see...
![image](https://user-images.githubusercontent.com/1536454/55970865-d08a7f80-5c99-11e9-9b87-9515b8581fa4.png)

I was expecting...
It should start editing from left to right 
#### Browsers

- [] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 2.2.4
- yii2-money version: 1.2.3

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/money)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-money without other plugins.

**Comment by kartik-v** [comment]
Suggest if you can use [yii2-number](http://demos.krajee.com/number) extension instead of yii2-money - which is not being enhanced and the source plugin has inherent issues.

**Comment by buttflattery** [comment]
ok, thanks for the input. will look into that extension tomorrow.
