### ISSUE TITLE
MaskMoney repeating values

### ISSUE THREAD

**Issue by thiagomoraesp** [kartik-v/yii2-money#36]
Hi, im having a issue with the mask money plugin, the displayed value is ok, but when i save i got the two last numbers duplicade, for example:

On the form: 123,45
On the post: 12345,45

here is my implementation of the maskmoney:

https://pastebin.com/j0dj1ydZ

Thanks :)

**Comment by thiagomoraesp** [comment]
Another info, when the value have thousand separator, (greater than 1000) the problem doesn't occour.

**Comment by kartik-v** [comment]
Suggest to use the yii2-number extension which has replaced yii2-money.  The yii2-number extension is better and simpler to use and does not have problems which the maskmoney plugin has.
