### ISSUE TITLE
Enter not work 

### ISSUE THREAD

**Issue by nepster-web** [kartik-v/yii2-money#4]
Hi.

YII-money works with mouse-click event but doesn't with Enter, it throws an error:
![Demo](http://c2n.me/iRm4MM.png)

**Comment by kartik-v** [comment]
Resolved via [updates & enhancements to release v1.2.2](https://github.com/kartik-v/yii2-money/commit/6c18c47b6561e52ecd4cff9d2e0c3a0e974c236f). Duplicate to #24, #17, #12.
